#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  export CC="$(basename "$(which clang gcc | head -1)")"

  mkdir -p "$PACKAGES" "$WRKOBJDIR" "$DISTDIR"
  rm -rf $WRKOBJDIR/bootstrap $PACKAGES/bootstrap.tgz

  (cd $shome/vendor/pkgsrc/bootstrap && \
    $PKG_OPT ./bootstrap --prefix=$PKG_HOME/install --unprivileged --abi 64 \
      --prefer-pkgsrc=yes --ignore-user-check -j4 --compiler=$CC \
      --mk-fragment=$PKG_HOME/etc/mk.conf \
      --workdir $WRKOBJDIR/bootstrap \
      --gzip-binary-kit $PACKAGES/bootstrap.tgz \
  )
  echo info tar xvfz $PACKAGES/bootstrap.tgz -C /
}

bootstrap
