#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export CC="$(basename "$(which clang gcc | head -1)")"

  local nm_pkg
  for nm_pkg in "$@"; do
    if pushd "$shome/vendor/pkgsrc/$nm_pkg" 2>/dev/null >/dev/null; then
      $BMAKE "${PKG_TARGET:-install}"
      popd >/dev/null
    fi
  done
}

source sub "$BASH_SOURCE" "$@"
