#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export CC="$(basename "$(which clang gcc | head -1)")"

  mkdir -p "$PACKAGES" "$WRKOBJDIR" "$DISTDIR"
  rm -rf $WRKOBJDIR/bootstrap $PACKAGES/bootstrap.tgz

  (cd $PKGSRCDIR/bootstrap && \
    $PKG_OPT ./bootstrap --prefix=$PKG_HOME/install --unprivileged --abi 64 \
      --prefer-pkgsrc=yes --ignore-user-check -j4 --compiler=$CC \
      --mk-fragment=$HOME/etc/mk.conf \
      --workdir $WRKOBJDIR/bootstrap \
      $(if [[ "${PKG_TARGET:-}" == "package" ]]; then echo --gzip-binary-kit $PACKAGES/bootstrap.tgz; fi) \
  )
}

source sub "$BASH_SOURCE" "$@"
