#!/usr/bin/env bash

function main {
  local shome="${_pkgsrc_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  $PKG_OPT pkg_chk -u -q
}

source sub "$0" "$@"
