#!/usr/bin/env bash

function main {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bmake)
        PKG_TARGET=package app compile bmake
        ;;
      *)
        PKG_TARGET=package app compile pkgsrc "$nm_pkg"
        ;;
    esac
  done
}

source sub "$0" "$@"
