#!/usr/bin/env bash

function install_pkg {
  pkgin -y install "$1"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  local nm_pkg="$1"; shift
  local nm_build="${1:-$nm_pkg}"

  if [[ ! -d "$PKGSRCDIR" ]]; then
    pushd "${BOARD_PATH}"
      if [[ -f "${DATA}/cache/git/${PKGSRC_BRANCH}.tar.gz" ]]; then
        tar xfz "${DATA}/cache/git/${PKGSRC_BRANCH}.tar.gz"
      fi
    popd
  fi

  case "$nm_build" in
    bootstrap)
      if ! pkg install "$nm_build"; then
        if [[ -z "${PKG_BUILD_SOURCE:-}" ]]; then
          return 1
        fi

        pkg package "$nm_build"
      fi
      pkg_add -f "$(set +f; ls -trhd "${PACKAGES}/All/"pkgin-*.tgz 2>/dev/null | tail -1)" 2>/dev/null || true
      ;;
    *)
      pkg update cache
      install_pkg just-importing-summary >/dev/null 2>&1 || true

      if ! type -P pkgin >/dev/null || ! install_pkg "${nm_pkg#*/}"; then
        if [[ -z "${PKG_BUILD_SOURCE:-}" ]]; then
          return 1
        fi

        if type -P pkgin >/dev/null; then
          if ! install_pkg "${nm_pkg#*/}"; then
            pkg package "$nm_build"
            pkg update cache
            install_pkg "${nm_pkg#*/}"
          fi
        else
          pkg bin-install "$nm_build"
        fi
      fi
      ;;
  esac
  pkg update cache
}

source sub "$0" "$@"
