#!/usr/bin/env bash

function main {
  local shome="${_pkgsrc_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg_chk -u -s -P "$PACKAGES" 
}

source sub "$0" "$@"
