#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bootstrap)
        if [[ ! -d "$PKG_HOME" ]]; then
          sudo install -d -o $(id -un) -g $(id -gn) -m 755 "$PKG_HOME"
        fi
        tar xvfz "$PACKAGES/bootstrap.tgz" -C /
        ;;
      *)
        PKG_TARGET=install block compile pkgsrc "$nm_pkg"
        ;;
    esac
  done
}

source sub "$0" "$@"
