#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkgin -p ls | cut -d';' -f1  | perl -pe 's{-[^-\s]+$}{}' | sort -u
}

source sub "$0" "$@"
