#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  $PKG_OPT pkg_chk -u -q
}

source sub "$0" "$@"
