#!/usr/bin/env bash

function install_pkg {
  if type -P localhost >/dev/null && type -P ansible >/dev/null; then
    localhost -m pkgin -- name="$1"
  else
    pkgin -y install "$1"
  fi
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg="$1"; shift
  local nm_build="${1:-$nm_pkg}"

  case "$nm_build" in
    bootstrap)
      if ! pkg install "$nm_build"; then
        if [[ -z "${PKG_BUILD_SOURCE:-}" ]]; then
          return 1
        fi

        pkg package "$nm_build"
      fi
      if pkg_add -f "$(set +f; ls -trhd "${PACKAGES}/All/"pkgin-*.tgz 2>/dev/null | tail -1)" 2>/dev/null; then
        pkg update cache
      fi
      ;;
    *)
      install_pkg just-importing-summary >/dev/null 2>&1 || true

      if ! type -P pkgin >/dev/null || ! install_pkg "${nm_pkg#*/}"; then
        if [[ -z "${PKG_BUILD_SOURCE:-}" ]]; then
          return 1
        fi

        if type -P pkgin >/dev/null; then
          if ! install_pkg "${nm_pkg#*/}"; then
            if [[ ! -d "$shome/vendor/pkgsrc" ]]; then
              git clone --depth 1 -b "${PKGSRC_BRANCH}" "file://$shome/vendor/pkgsrc-mirror" "$shome/vendor/pkgsrc"
            fi
            pkg package "$nm_build"
            pkg update cache
            install_pkg "${nm_pkg#*/}"
          fi
        else
          pkg bin-install "$nm_build"
          pkg update cache
        fi
      fi
      ;;
  esac
}

source sub "$0" "$@"
