#!/usr/bin/env bash

function main {
  local shome="${_pkgsrc_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bootstrap)
        echo "ERROR: dont know how to upgrade bookstrap, yet" 1>&2
        return 1
        ;;
      *)
        PKG_TARGET=update block compile pkgsrc "$nm_pkg"
        ;;
    esac
  done
}

source sub "$0" "$@"
