#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  rm -f pkgsrc.tar.gz
  wget http://cdn.netbsd.org/pub/pkgsrc/${PKGSRC_BRANCH_DIR}/pkgsrc.tar.gz
  mv pkgsrc.tar.gz "${PKGSRC_BRANCH}.tar.gz"
  rm -rf "${PKGSRC_BRANCH}"
  tar xfz "${PKGSRC_BRANCH}.tar.gz"
  rm -f "${PKGSRC_BRANCH}.tar.gz"
  mv pkgsrc "$PKGSRC_BRANCH"

  $PKG_OPT pkg_chk -g
}

source sub "$0" "$@"
