#!/usr/bin/env bash

function main {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    PKG_TARGET=clean app compile pkgsrc "$1"
  done
}

source sub "$0" "$@"
