#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  local nm_pkg="$1"; shift
  pkg clean "$nm_pkg"
  PKG_TARGET=replace block compile pkgsrc "$nm_pkg"
}

source sub "$0" "$@"


