#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bootstrap)
        env PKG_TARGET=package block compile bmake
        ;;
      *)
        env PKG_TARGET=package block compile pkgsrc "$nm_pkg"
        ;;
    esac
  done
}

source sub "$0" "$@"
