#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pushd "$shome/vendor/pkgsrc"
  git fetch
  git reset --hard origin/master
  popd
  pkg_admin -K "$PKG_HOME/install/var/db/pkg" fetch-pkg-vulnerabilities

  if [[ -x "$(which brew 2>/dev/null || true)" ]]; then
    brew update
  fi

  if [[ -x "$(which aptitude 2>/dev/null || true)" ]]; then
    sudo aptitude update
  fi
}

source sub "$0" "$@"
