#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bootstrap)
        block compile bmake
        ;;
      *)
        PKG_TARGET=install block compile pkgsrc "$nm_pkg"
        ;;
    esac
  done
}

source sub "$0" "$@"
