#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    cat "$PKGSRCDIR/$nm_pkg/DESCR"
  done
}

source sub "$0" "$@"
