#!/usr/bin/env bash

function main {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    cat "$shome/vendor/pkgsrc/$nm_pkg/DESCR"
  done
}

source sub "$0" "$@"
