#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_pkg
  for nm_pkg in "$@"; do
    case "$nm_pkg" in
      bootstrap)
        tar xvfz "$PACKAGES/bootstrap.tgz" -C /
        ;;
      *)
        export PKG_PATH="$PACKAGES/All"
        (cd $PACKAGES; $PKGADD "$nm_pkg")
        ;;
    esac
  done
}

source sub "$0" "$@"
