#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"
  source normalize

  mkdir -p "$(dirname "${DISTDIR}")" || sudo install -d -o $(id -un) -g $(id -gn) "$(dirname "${DISTDIR}")"
  mkdir -p "$DISTDIR" "$PACKAGES"

  if [[ "$#" == 0 ]]; then
    set -- "${PACKAGES}/All"
  fi

  while [[ "$#" -gt 0 ]]; do
    cd "$1"; shift

    if type -P pkg_info >/dev/null; then
      (set +f; pkg_info -X *.tgz) | gzip -9 > pkg_summary.gz.$$
      mv -f pkg_summary.gz.$$ pkg_summary.gz
    fi
    if type -P pkgin >/dev/null; then
      pkgin update
    fi
  done
}

source sub "$0" "$@"
