#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  git clone -b pkgsrc_2015Q3 git@github.com:defn/pkgsrc "$shome/vendor/pkgsrc"
}

bootstrap
