#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ -z "${PKG_HOME:-}" ]]; then
    return 0
  fi

  if [[ ! -d "$PKGSRCDIR" ]]; then
    git clone -b "${PKGSRC_BRANCH}" "https://github.com/NetBSD/pkgsrc"  "$PKGSRCDIR"
  fi

  if [[ ! -d "$PKGWIPDIR" ]]; then
    git clone -b "${PKGWIP_BRANCH}" "https://github.com/joyent/pkgsrc-wip"  "$PKGWIPDIR"
  fi

  install -d "$PKG_HOME"

  pkg ensure bootstrap

  mkdir -p "$PKG_HOME/install/include"
  ln -nfs gettext/libintl.h "$PKG_HOME/install/include/"
  for nm_pkg in devel/ncurses devel/ncursesw devel/gettext-tools devel/gettext textproc/openjade; do
    if ! pkg ensure "$nm_pkg"; then
      case "${DISTRIB_ID}" in
        Darwin)
          set +f
          pushd "$WRKOBJDIR/$nm_pkg"/work/*/
          set -f
          env CWRAPPERS_CONFIG_DIR=$(pwd)/../.cwrapper/config bmake || env CWRAPPERS_CONFIG_DIR=$(pwd)/../.cwrapper/config make
          popd
          pkg ensure "$nm_pkg"
          ;;
        *)
          return 1
          ;;
      esac
    fi
  done

  pkg ensure pkgtools/pkgin
  pkg ensure pkgtools/pkg_chk

  pkgin update

  pkg ensure security/mozilla-rootcerts
  mozilla-rootcerts install || true
  pushd $PKG_HOME/install/etc/openssl/certs
  mozilla-rootcerts extract
  mozilla-rootcerts rehash
  popd

  pkg ensure misc/getopt
  pkg ensure net/wget
  pkg ensure www/curl
  pkg ensure devel/gmake
  pkg ensure devel/gettext-tools
}

main "$@"
