#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  if [[ ! -x "$PKG_HOME/install/bin/bmake" ]]; then
    return 1
  fi

  if ! type -P pkgin >/dev/null; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
