#!/usr/bin/env bash

function main {
  local shome="${_pkgsrc_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ ! -x "$PKG_HOME/install/bin/bmake" ]]; then
    return 1
  fi

  if [[ ! -d "$shome/vendor/pkgsrc/.git" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
