#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/script/profile-reset"

  for a in bmake gtar pkgin lintpkgsrc; do 
    if [[ ! -x "$PKG_HOME/install/bin/$a" ]]; then
      return 1
    fi
  done

  return 0
}

source sub "$0" "$@"
