#!/usr/bin/env bash

function id_install {
  local nm_os
  case "$(uname -s)" in
    Darwin|Linux)
      nm_os="$(uname -s)_$(uname -r | cut -d- -f1 | cut -d. -f1-3)"
      ;;
    *)
      nm_os="$(uname -s)"
      ;;
  esac

  echo "$nm_os/$PKG_HOME/$PKGSRC_BRANCH" | tr / _ | tr . _ | perl -pe 's{__+}{_}'
}

function _pkgsrc_profile {
  local shome="${_pkgsrc_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"

  if [[ -z "${PKG_HOME:-}" ]]; then
    PATH="$shome/bin:$shome/exec:$PATH"
    return 0
  fi

  PATH="$shome/bin:$PKG_HOME/install/sbin:$PKG_HOME/install/bin:$PKG_HOME/install/gnu/bin:$shome/exec:$PATH"

  export PKGSRC_BRANCH='pkgsrc_2016Q2'

  local pth_cache="${BASEBOX_CACHE:-/vagrant}"

  export ID_INSTALL="$(id_install)"

  export DISTDIR="$pth_cache/distfiles"

  export PACKAGES="$shome/vendor/pkgsrc/packages"

  export PKG_OPT="env MAKEFLAGS= MFLAGS= DISTDIR=$DISTDIR PACKAGES=$PACKAGES PKG_RCD_SCRIPTS=no SKIP_LICENSE_CHECK=yes"

  export BMAKE="$PKG_OPT bmake"

  export SH="$(which bash)"

  export PKGSRCDIR="$shome/vendor/pkgsrc"
}

_pkgsrc_profile
