#!/usr/bin/env bash

function id_install {
  local nm_os="${DISTRIB_ID}_$(uname -r | cut -d- -f1 | cut -d. -f1-2)"
  echo "$nm_os/$PKG_HOME/$PKGSRC_BRANCH" | tr / _ | tr . _ | perl -pe 's{__+}{_}'
}

function _pkgsrc_profile {
  local shome="${_pkgsrc_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"

  if [[ -z "${PKG_HOME:-}" ]]; then
    export PKG_HOME="${BOARD_PATH:-$HOME}"
  fi

  PATH="$shome/bin:$PKG_HOME/install/sbin:$PKG_HOME/install/bin:$PKG_HOME/install/gnu/bin:$shome/exec:$PATH"

  export PKGSRC_BRANCH='pkgsrc-2017Q3'
  export PKGWIP_BRANCH='2017Q3'

  local pth_cache="${DATA}/cache"

  export ID_INSTALL="$(id_install)"

  export DISTDIR="$pth_cache/distfiles"

  export PACKAGES="$pth_cache/packages/${ID_INSTALL}"
  export WRKOBJDIR="${TMP:-${TMPDIR:-/tmp}}/pkgsrc_${ID_INSTALL}"

  export PKG_OPT="env MAKEFLAGS= MFLAGS= DISTDIR=$DISTDIR WRKOBJDIR=$WRKOBJDIR PACKAGES=$PACKAGES PKG_RCD_SCRIPTS=no SKIP_LICENSE_CHECK=yes"

  export BMAKE="$PKG_OPT bmake"

  export SH="$(which bash)"

  export PKGSRCDIR="${BOARD_PATH}/${PKGSRC_BRANCH}"
  export PKGWIPDIR="${BOARD_PATH}/${PKGSRC_BRANCH}-wip"

  export PKG_REPOS="file://$PACKAGES/All"

  export PKG_BUILD_SOURCE=1
}

_pkgsrc_profile
