#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  (cd "$PKGSRCDIR" && git checkout -b "${PKGSRC_BRANCH}" 2>/dev/null)
  (cd "$PKGSRCDIR" && git reset --hard "origin/${PKGSRC_BRANCH}")
  (cd "$PKGSRCDIR" && git pull)

  (cd "$PKGWIPDIR" && git checkout -b "${PKGWIP_BRANCH}" 2>/dev/null)
  (cd "$PKGWIPCDIR" && git reset --hard "origin/${PKGWIP_BRANCH}")
  (cd "$PKGWIPDIR" && git pull)

  mkdir -p "$PKG_HOME/install/var/db/pkg"
  pkg_admin -K "$PKG_HOME/install/var/db/pkg" fetch-pkg-vulnerabilities

  pkg update list
}

main "$@"
