#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -d "$shome/vendor/pkgsrc" ]]; then
    git clone --depth 1 -b "${PKGSRC_BRANCH}" "file://$shome/vendor/pkgsrc-mirror"  "$shome/vendor/pkgsrc"
  fi

  (cd "$shome/vendor/pkgsrc-mirror" && git fetch origin "${PKGSRC_BRANCH}:${PKGSRC_BRANCH}")
  (cd "$shome/vendor/pkgsrc" && git checkout -b "${PKGSRC_BRANCH}")
  (cd "$shome/vendor/pkgsrc" && git reset --hard origin/"${PKGSRC_BRANCH}")

  pkg_admin -K "$PKG_HOME/install/var/db/pkg" fetch-pkg-vulnerabilities
}

main "$@"
