#!/usr/bin/env bash

function main {
  local shome="${_pkgsrc_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$PKG_HOME/install/bin/bmake" ]]; then
    if [[ -d "$shome/vendor/pkgsrc" ]]; then
      return 1
    fi
  fi

  return 0
}

source sub "$0" "$@"
