#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$(type -P bmake)" ]]; then
    if [[ -d "$shome/vendor/pkgsrc" ]]; then
      if [[ -d "$shome/vendor/pkgsrc-wip" ]]; then
        return 1
      fi
    fi
  fi

  return 0
}

source sub "$0" "$@"
