#!/usr/bin/env bash

function update {
  local shome="${_pkgsrc_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  ln -nfs "$PACKAGES/All" "$shome/vendor/pkgsrc/All"
  (cd "$shome/vendor/pkgsrc"; set +f; for a in *; do if [[ "$a" != "All" ]]; then ln -nfs All "$PACKAGES/$a"; fi; done)
  if [[ -d "${BASEBOX_CACHE}/packages/${ID_INSTALL}/All" ]]; then
    cd "${BASEBOX_CACHE}/packages/${ID_INSTALL}/All"
    pkg_info -X *.tgz | gzip -9 > pkg_summary.gz.$$
    mv -f pkg_summary.gz.$$ pkg_summary.gz
  fi
}

update
